const path = require("path");
const glob = require("glob");
const Webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const TerserPlugin = require("terser-webpack-plugin");
const {CleanWebpackPlugin} = require("clean-webpack-plugin");
const CssMinimizerPlugin = require("css-minimizer-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const PurgeCssPlugin = require("purgecss-webpack-plugin");
const JsonMinimizerPlugin = require("json-minimizer-webpack-plugin");
const CompressionPlugin = require("compression-webpack-plugin");

const createConfig = (parentDir, srcDir, buildDir, env, options = {enableGzipCompression: true}) => {
    const envVariables = {}
    if (env) {
      Object.keys(env).map(key => envVariables[key] = `'${env[key]}'`)
    }

    return {
      mode: "production",
      entry: ["@babel/polyfill", path.join(srcDir, "index.tsx")],
      output: {
        path: buildDir,
        filename: "[name].[fullhash:8].bundle.js",
        // sourceMapFilename: "[name].[fullhash:8].bundle.js.map",
        chunkFilename: "[name].[fullhash:8].chunk.js",
        publicPath: "/"
      },
      performance: {
        hints: false,
        maxEntrypointSize: 512000,
        maxAssetSize: 512000
      },
      // devtool: "hidden-source-map",
      devServer: {
        static: buildDir,
        port: 8081,
        historyApiFallback: true,
        open: true,
        compress: true
      },
      resolve: {
        extensions: ["*", ".js", ".jsx", ".json", ".ts", ".tsx"],
        alias: {
          "@": srcDir // shortcut to reference src folder from anywhere
        },
        fallback: {
          'react/jsx-runtime': 'react/jsx-runtime.js',
          'react/jsx-dev-runtime': 'react/jsx-dev-runtime.js',
        }
      },
      module: {
        rules: [{
          test: /\.(ts|tsx)$/,
          loader: "ts-loader",
        }, {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader",
            options: {      // The object assigned to "option" field can alternatively moved to ".babelrc" file
              presets: [
                "@babel/preset-env",
                "@babel/preset-react"
              ],
              plugins: [
                "@babel/plugin-proposal-class-properties",
                "@babel/plugin-proposal-optional-chaining"
              ]
            }
          }
        }, {
          test: /\.html$/,
          use: "html-loader"
        }, {
          test: /\.handlebars/,
          use: "handlebars-loader",
          exclude: /node_modules/
        }, {
          test: /\.css$/,
          use: [{
            loader: MiniCssExtractPlugin.loader,
            options: {
              esModule: true
            }
          }, {
            loader: "css-loader",
            options: {
              sourceMap: false
            }
          }],
        }, {
          test: /\.scss$/,
          use: [MiniCssExtractPlugin.loader, "css-loader", "sass-loader"]
        }, {
          test: /\.(png|svg|jpg|jpeg|gif)$/,
          use: [{
            loader: "file-loader",
            options: {
              outputPath: "images",
            }
          }],
        }, {
          test: /\.(woff|woff2|eot|ttf|otf)$/,
          use: [{
            loader: "file-loader",
            options: {
              outputPath: "fonts",
            }
          }],
        }]
      },
      plugins: [
        new Webpack.DefinePlugin({
          "process.env": envVariables
        }),
        new HtmlWebpackPlugin({
          template: path.join(parentDir, "public/index.hbs"),
          inject: true,
          process: {
            env: {
              ...envVariables
            }
          },
          minify: {
            collapseBooleanAttributes: true,
            collapseInlineTagWhitespace: true,
            collapseWhitespace: true,
            conservativeCollapse: true,
            html5: true,
            includeAutoGeneratedTags: true,
            removeComments: true,
            removeRedundantAttributes: true,
            removeScriptTypeAttributes: true,
            removeStyleLinkTypeAttributes: true,
            useShortDoctype: true
          }
        }),
        new MiniCssExtractPlugin({
          filename: "[name].[fullhash:8].css",
          chunkFilename: "[id].[name].[fullhash:8].chunk.css",
        }),
        new PurgeCssPlugin.PurgeCSSPlugin({
          paths: glob.sync(`${srcDir}/**/*`, {nodir: true}),
        }),
        new CleanWebpackPlugin(),
        options.enableGzipCompression ? (
          new CompressionPlugin({
            algorithm: "gzip",
          })
        ) : undefined
      ],
      optimization: {
        minimize: true,
        splitChunks: {
          chunks: "all",
        },
        minimizer: [
          new JsonMinimizerPlugin(),
          new CssMinimizerPlugin({
            minimizerOptions: {
              preset: ["default", {discardComments: {removeAll: true}}],
            },
            parallel: true
          }),
          new TerserPlugin({
            parallel: true,
            extractComments: true,
            terserOptions: {
              ecma: 2020,
              compress: true,
              mangle: true,
              format: {
                comments: false
              }
            }
          })
        ],
      }
    }
  }
;

module.exports = createConfig
